version: '3.7'

services:
  db:
    container_name: 'sanatopia-db'
    image: postgres:14
    restart: always
    ports: 
      - 5432:5432  
    environment:
      - POSTGRES_USER=sanatopia
      - POSTGRES_PASSWORD=sanatopia
      - POSTGRES_DB=sanatopia
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - db
      
volumes:
  postgres:
  
networks:
  db:
    driver: bridge